### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by adeptio** [adeptio/pellagraph#2]

**Comment by adeptio** [comment]
Ready for review

**Comment by chungkikelly** [comment]
Demo log in actually fires a regular log in event first, prior to demo log in (so if you fill out the form with correct credentials and hit demo, you'll log in as the user that corresponds to the form data)

**Comment by adeptio** [comment]
added e.preventDefault to handleDemo function

**Comment by chungkikelly** [comment]
After all MVP's are completed - we should consider styling the landing page + login / signup forms. Otherwise, functionality is all there!
