### ISSUE TITLE
SourcesController: index method error

### ISSUE THREAD

**Issue by adeptio** [adeptio/pellagraph#29]
Delete source correctly deletes source from db, but doesn't updates source index display immediately.    

def index
    @sources = Source.where(author_id: current_user.id)
    render :index
  end

- @sources does not seem to be getting populated by the query, which causes an error in the jbuilder because '.each' cannot be called on nil.  
    - The query returns the correct objects when run in the rails console, not sure why they aren't detected in jbuilder.
    - verified that current_user.id is correct in rails console.

**Comment by chungkikelly** [comment]
Throw a debugger before `render :index` in the aforementioned code to see if `@sources` is correctly populated. If it's not, then check to make sure `current_user` is what we assume it is.

**Comment by chungkikelly** [comment]
Also, check to make sure the instance variable used in the index.json.jbuilder is `@sources` - possible there's a typo and we're just not passing in the correct variable.

**Comment by adeptio** [comment]
refactored backend jbuilders and controller to only send id to delete, not index
