### ISSUE TITLE
PA Review: Supports JSON, TSV, and CSV formats

### ISSUE THREAD

**Issue by adeptio** [adeptio/pellagraph#3]

**Comment by chungkikelly** [comment]
When attempting to upload any of the file types, the console will throw a unique error (depending on which file type is attempted).

**Comment by adeptio** [comment]
In pellagraph/frontend/components/sources/source_show.jsx, render is called with the props of the source_index page (which it currently expects and knows how to handle), then again on the source_show page with different props that it doesn't expect.  fixing now.

**Comment by adeptio** [comment]
fixed the uncaught type error and re-pushed to heroku, was that the error you saw - or was it a different one?  I only see a few warnings.

**Comment by adeptio** [comment]
Hmm, I've tried re-creating your file and uploading it - to no avail.  It seems to be an error with papaparse, but not sure why it handles my bigger tsv files successfully.

**Comment by chungkikelly** [comment]
Perhaps the tsv file I have is formatted differently? Can you send me your tsv file so I can try uploading it?

**Comment by adeptio** [comment]
hmm, github won't load tsv - should I send it via email?

**Comment by chungkikelly** [comment]
TSV working now - all good.
