### ISSUE TITLE
Seed File

### ISSUE THREAD

**Issue by adeptio** [adeptio/pellagraph#37]
- Demo user, other users.
- shares

**Comment by chungkikelly** [comment]
Assumed this was done, because demo user works. Please assign to me when you've seeded your user data base.

**Comment by adeptio** [comment]
will do, wasn't trying to fool you - just doing more testing!

**Comment by adeptio** [comment]
Done

**Comment by chungkikelly** [comment]
Didn't think you were - just closed it accidentally.
