### ISSUE TITLE
PA Review: Upload data and visualize it with a variety of charts

### ISSUE THREAD

**Issue by adeptio** [adeptio/pellagraph#6]

**Comment by adeptio** [comment]
Ready for review

**Comment by chungkikelly** [comment]
Looks good to go - assuming we can upload data correctly.

**Comment by adeptio** [comment]
Yeah, I can upload data of the three formats successfully on heroku - but I do get the uncaught typeerror you mentioned in https://github.com/adeptio/pellagraph/issues/3 - looking into it.
